[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MLOps Pipeline Deployment"
authors = [{name = "PierreExeter", email = "pierre@exeter"}]
dynamic = ["version", "description"]
